stages:
 - maventry
 - androidtry

maven-build:
 stage: maventry
 tags:
  - springboot_tag
 script:
  - cd Backend/kokottni/Data
  - mvn package

android-build:
 image: gjandres/android-ci:latest
 stage: androidtry
 tags:
  - android_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app
 script:
  - cd Frontend/frontend_app/app/src
  - ./gradlew assemble
