stages:
 - maventry
 - androidtry 
 - androidbuild
 - androidtest

maven-build:
 stage: maventry
 tags:
  - springboot_tag
 script:
  - cd Backend/kokottni/Data
  - mvn package

androidtry:
 image: alpine:latest
 stage: androidtry
 tags:
  - android_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
 script:
  - cd Frontend/frontend_app
  - ./gradlew assemble

android-build:
 image: alpine:latest
 stage: androidbuild
 tags:
  - android_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
 script:
  - cd Frontend/frontend_app
  - ./gradlew build
 artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: alpine:latest
  stage: androidtest
  before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
  tags:
  - android_tag
  script:
  - cd Frontend/frontend_app
  - ./gradlew test
