stages:
 - androidbuild
 - androidtest

android-build:
 image: alpine:latest
 stage: androidbuild
 tags:
  - skutsch_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
 script:
  - cd Frontend/frontend_app/gradlew
  - ./gradlew build

android-test:
  image: alpine:latest
  stage: androidtest
  tags:
  - skutsch_tag
  before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
  script:
  - cd Frontend/frontend_app
  - ./gradlew test
