stages:
 - maventry
<<<<<<< HEAD
 - androidtry 
=======
 - maventest
 - mavenDeploy
>>>>>>> 191389b4fb0d629af4bb8dd5922a41e6df9f8564
 - androidbuild
 - androidtest

maven-build:
 stage: maventry
 tags:
  - springboot_tag
 script:
  - cd Backend/kokottni/Data
  - mvn package

<<<<<<< HEAD
androidtry:
 image: alpine:latest
 stage: androidtry
 tags:
  - android_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
 script:
  - cd Frontend/frontend_app
  - ./gradlew assemble
=======
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/kokottni/Data
    - mvn test
  artifacts:
    paths:
      - Backend/kokottni/Data/target/*.jar

autoDeploy:
  stage: mavenDeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/kokottni/Data
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
>>>>>>> 191389b4fb0d629af4bb8dd5922a41e6df9f8564

android-build:
 image: alpine:latest
 stage: androidbuild
 tags:
  - android_tag
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
 script:
  - cd Frontend/frontend_app
  - ./gradlew build
 artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: alpine:latest
  stage: androidtest
  before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/frontend_app/gradlew
  tags:
  - android_tag
  script:
  - cd Frontend/frontend_app
  - ./gradlew test
